# Generated by Django 3.0.8 on 2020-08-19 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planteamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=24)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Pendiente', 'Pendiente'), ('Solucionado', 'Solucionado')], default='Nuevo', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencida', models.DateField(default=datetime.date(2020, 9, 2))),
                ('secretario', models.CharField(max_length=60)),
                ('clasificacion', models.CharField(choices=[('Territorial', 'Territorial'), ('Nacional', 'Nacional')], default='Territorial', max_length=12)),
                ('procesos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planteamientos.Procesos')),
                ('seccion_sindical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.SeccionSindical')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.UnidadOrganizativa')),
            ],
        ),
    ]
