# Generated by Django 4.0.5 on 2022-06-26 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planteamiento',
            name='fecha_vencida',
            field=models.DateField(default=datetime.date(2022, 7, 9)),
        ),
    ]
