# Generated by Django 4.0.5 on 2022-06-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteamientos', '0002_alter_planteamiento_fecha_vencida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planteamiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
