# Generated by Django 4.0.5 on 2022-07-02 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteamientos', '0003_alter_planteamiento_id_alter_procesos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planteamiento',
            name='estado',
            field=models.CharField(choices=[('Estancado', 'Estancado'), ('Nuevo', 'Nuevo'), ('Pendiente', 'Pendiente'), ('Solucionado', 'Solucionado')], default='Estancado', max_length=20),
        ),
        migrations.AlterField(
            model_name='planteamiento',
            name='fecha_vencida',
            field=models.DateField(default=datetime.date(2022, 7, 16)),
        ),
    ]
