# Generated by Django 4.0.5 on 2022-07-02 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planteamientos', '0004_alter_planteamiento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planteamiento',
            name='modificado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
