# Generated by Django 3.0.8 on 2020-08-19 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planteamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('validacion', models.BooleanField(default=False)),
                ('autor', models.CharField(max_length=10)),
                ('planteamiento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planteamientos.Planteamiento')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('aprobacion', models.BooleanField(default=False)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=100)),
                ('planteamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planteamientos.Planteamiento')),
            ],
        ),
    ]
